import {
  AUTOMATION_NODE_KIND_LABELS,
  AUTOMATION_SCOPE_EVENT_KINDS,
  AUTOMATION_SCOPE_TASK_STATUSES,
  CHAT_BACKENDS,
} from "@lilia/contracts";

export const NODE_KIND_LABELS = AUTOMATION_NODE_KIND_LABELS;

export const TASK_STATUS_OPTIONS = AUTOMATION_SCOPE_TASK_STATUSES;
export const BACKEND_OPTIONS = CHAT_BACKENDS;
export const TRIGGER_EVENT_KIND_OPTIONS = AUTOMATION_SCOPE_EVENT_KINDS;
