export const CHAT_COMMANDS_CONTRACT: {
  agentTimelineListCommand: "agent_timeline_list";
  agentTimelineClearTaskCommand: "agent_timeline_clear_task";
  chatSendMessageCommand: "chat_send_message";
  chatInterruptTurnCommand: "chat_interrupt_turn";
  chatDescribeAttachmentsCommand: "chat_describe_attachments";
  chatSearchContextAttachmentsCommand: "chat_search_context_attachments";
  chatSearchSlashCommandsCommand: "chat_search_slash_commands";
  chatReadClipboardFilePathsCommand: "chat_read_clipboard_file_paths";
  chatSaveClipboardImageCommand: "chat_save_clipboard_image";
  chatSaveClipboardTextCommand: "chat_save_clipboard_text";
  chatGetComposerStateCommand: "chat_get_composer_state";
  chatListModelsCommand: "chat_list_models";
  chatGetRuntimeSnapshotCommand: "chat_get_runtime_snapshot";
  chatSetComposerStateCommand: "chat_set_composer_state";
  chatAckRestoredRollbackCommand: "chat_ack_restored_rollback";
  chatRespondAgentInteractionCommand: "chat_respond_agent_interaction";
  chatRespondTitleUpdateCommand: "chat_respond_title_update";
  liliaIabOpenCommand: "lilia_iab_open";
  liliaIabSubmitCommand: "lilia_iab_submit";
};

export const AGENT_TIMELINE_LIST_COMMAND: "agent_timeline_list";
export const AGENT_TIMELINE_CLEAR_TASK_COMMAND: "agent_timeline_clear_task";
export const CHAT_SEND_MESSAGE_COMMAND: "chat_send_message";
export const CHAT_INTERRUPT_TURN_COMMAND: "chat_interrupt_turn";
export const CHAT_DESCRIBE_ATTACHMENTS_COMMAND: "chat_describe_attachments";
export const CHAT_SEARCH_CONTEXT_ATTACHMENTS_COMMAND: "chat_search_context_attachments";
export const CHAT_SEARCH_SLASH_COMMANDS_COMMAND: "chat_search_slash_commands";
export const CHAT_READ_CLIPBOARD_FILE_PATHS_COMMAND: "chat_read_clipboard_file_paths";
export const CHAT_SAVE_CLIPBOARD_IMAGE_COMMAND: "chat_save_clipboard_image";
export const CHAT_SAVE_CLIPBOARD_TEXT_COMMAND: "chat_save_clipboard_text";
export const CHAT_GET_COMPOSER_STATE_COMMAND: "chat_get_composer_state";
export const CHAT_LIST_MODELS_COMMAND: "chat_list_models";
export const CHAT_GET_RUNTIME_SNAPSHOT_COMMAND: "chat_get_runtime_snapshot";
export const CHAT_SET_COMPOSER_STATE_COMMAND: "chat_set_composer_state";
export const CHAT_ACK_RESTORED_ROLLBACK_COMMAND: "chat_ack_restored_rollback";
export const CHAT_RESPOND_AGENT_INTERACTION_COMMAND: "chat_respond_agent_interaction";
export const CHAT_RESPOND_TITLE_UPDATE_COMMAND: "chat_respond_title_update";
export const LILIA_IAB_OPEN_COMMAND: "lilia_iab_open";
export const LILIA_IAB_SUBMIT_COMMAND: "lilia_iab_submit";
