import {
  CONVERSATION_CONTEXT_CLAUDE_TOOL_NAME,
  CONVERSATION_CONTEXT_CONTRACT,
  CONVERSATION_CONTEXT_MCP_TOOL_NAME,
  CONVERSATION_CONTEXT_TOOL_NAME,
  CONVERSATION_CONTEXT_TOOL_NAMES,
  DEFAULT_CONVERSATION_CONTEXT_INCLUDE_MESSAGES,
  isLiliaConversationContextTool as isLiliaConversationContextToolImpl,
  MAX_CONVERSATION_CONTEXT_MESSAGES,
  MAX_CONVERSATION_CONTEXT_TEXT,
  QUERY_CONVERSATION_CONTEXT_INPUT_SCHEMA,
  type ConversationContextToolName as ContractConversationContextToolName,
} from "./conversationContextContract.mjs";

export {
  CONVERSATION_CONTEXT_CLAUDE_TOOL_NAME,
  CONVERSATION_CONTEXT_CONTRACT,
  CONVERSATION_CONTEXT_MCP_TOOL_NAME,
  CONVERSATION_CONTEXT_TOOL_NAME,
  CONVERSATION_CONTEXT_TOOL_NAMES,
  DEFAULT_CONVERSATION_CONTEXT_INCLUDE_MESSAGES,
  MAX_CONVERSATION_CONTEXT_MESSAGES,
  MAX_CONVERSATION_CONTEXT_TEXT,
  QUERY_CONVERSATION_CONTEXT_INPUT_SCHEMA,
};

export type ConversationContextToolName = ContractConversationContextToolName;

export const isLiliaConversationContextTool =
  isLiliaConversationContextToolImpl as (
    toolName: unknown,
  ) => toolName is ConversationContextToolName;
