export const MEMORY_COMMANDS_CONTRACT: Record<string, unknown>;
export const MEMORY_LIST_COMMAND: "memory_list";
export const MEMORY_UPSERT_COMMAND: "memory_upsert";
export const MEMORY_SET_ENABLED_COMMAND: "memory_set_enabled";
export const MEMORY_DELETE_COMMAND: "memory_delete";
export const MEMORY_GET_SETTINGS_COMMAND: "memory_get_settings";
export const MEMORY_SET_SETTINGS_COMMAND: "memory_set_settings";
export const MEMORY_GET_INJECTION_STATE_COMMAND: "memory_get_injection_state";
export const MEMORY_SET_TASK_ENABLED_COMMAND: "memory_set_task_enabled";
export const MEMORY_RESET_TASK_COOLDOWN_COMMAND: "memory_reset_task_cooldown";
