export const PROJECT_COMMANDS_CONTRACT: Record<string, unknown>;
export const PROJECT_LIST_COMMAND: "project_list";
export const PROJECT_DASHBOARD_LIST_COMMAND: "project_dashboard_list";
export const PROJECT_GET_COMMAND: "project_get";
export const PROJECT_CREATE_COMMAND: "project_create";
export const PROJECT_RENAME_COMMAND: "project_rename";
export const PROJECT_REMOVE_COMMAND: "project_remove";
export const PROJECT_TOGGLE_PIN_COMMAND: "project_toggle_pin";
export const PROJECT_REORDER_COMMAND: "project_reorder";
export const PROJECT_GET_SETTINGS_COMMAND: "project_get_settings";
export const PROJECT_SET_SETTINGS_COMMAND: "project_set_settings";
export const WORKTREE_LIST_COMMAND: "worktree_list";
export const WORKTREE_GET_FOR_TASK_COMMAND: "worktree_get_for_task";
export const WORKTREE_CLEAR_TASK_COMMAND: "worktree_clear_task";
export const WORKTREE_CREATE_FOR_TASK_COMMAND: "worktree_create_for_task";
export const WORKTREE_ATTACH_TASK_COMMAND: "worktree_attach_task";
export const WORKTREE_CLEANUP_ARCHIVE_COMMAND: "worktree_cleanup_archive";
export const WORKTREE_MERGE_DELETE_ARCHIVE_COMMAND: "worktree_merge_delete_archive";
