import {
  PROMPT_ASSISTANT,
  PROMPT_AUTOMATION,
  PROMPT_CLAUDE,
  PROMPT_CODEX,
  PROMPT_CONTRACT,
  PROMPT_MAIN_AGENT,
  PROMPT_RUNNER,
  PROMPT_SUGGESTION,
  PROMPT_TITLE,
} from "./promptContract.mjs";

export {
  PROMPT_ASSISTANT,
  PROMPT_AUTOMATION,
  PROMPT_CLAUDE,
  PROMPT_CODEX,
  PROMPT_CONTRACT,
  PROMPT_MAIN_AGENT,
  PROMPT_RUNNER,
  PROMPT_SUGGESTION,
  PROMPT_TITLE,
};
