export const PROVIDER_COMMANDS_CONTRACT: {
  chatCheckEnvCommand: "chat_check_env";
  providerGetConfigCommand: "provider_get_config";
  providerSetConfigCommand: "provider_set_config";
  providerGetActiveBackendCommand: "provider_get_active_backend";
  providerSetActiveBackendCommand: "provider_set_active_backend";
  providerCodexAppServerCheckUpdateCommand: "provider_codex_app_server_check_update";
  providerCodexAppServerInstallUpdateCommand: "provider_codex_app_server_install_update";
  providerCodexAccountStartLoginCommand: "provider_codex_account_start_login";
  routerGetModeCommand: "router_get_mode";
  routerSetModeCommand: "router_set_mode";
  assistantAiGetConfigCommand: "assistant_ai_get_config";
  assistantAiSetConfigCommand: "assistant_ai_set_config";
  assistantAiFetchModelsCommand: "assistant_ai_fetch_models";
  modelFeatureGetSettingsCommand: "model_feature_get_settings";
  modelFeatureSetSettingsCommand: "model_feature_set_settings";
  assistantAiTestConnectionCommand: "assistant_ai_test_connection";
  assistantAiOptimizePromptCommand: "assistant_ai_optimize_prompt";
};

export const CHAT_CHECK_ENV_COMMAND: "chat_check_env";
export const PROVIDER_GET_CONFIG_COMMAND: "provider_get_config";
export const PROVIDER_SET_CONFIG_COMMAND: "provider_set_config";
export const PROVIDER_GET_ACTIVE_BACKEND_COMMAND: "provider_get_active_backend";
export const PROVIDER_SET_ACTIVE_BACKEND_COMMAND: "provider_set_active_backend";
export const PROVIDER_CODEX_APP_SERVER_CHECK_UPDATE_COMMAND: "provider_codex_app_server_check_update";
export const PROVIDER_CODEX_APP_SERVER_INSTALL_UPDATE_COMMAND: "provider_codex_app_server_install_update";
export const PROVIDER_CODEX_ACCOUNT_START_LOGIN_COMMAND: "provider_codex_account_start_login";
export const ROUTER_GET_MODE_COMMAND: "router_get_mode";
export const ROUTER_SET_MODE_COMMAND: "router_set_mode";
export const ASSISTANT_AI_GET_CONFIG_COMMAND: "assistant_ai_get_config";
export const ASSISTANT_AI_SET_CONFIG_COMMAND: "assistant_ai_set_config";
export const ASSISTANT_AI_FETCH_MODELS_COMMAND: "assistant_ai_fetch_models";
export const MODEL_FEATURE_GET_SETTINGS_COMMAND: "model_feature_get_settings";
export const MODEL_FEATURE_SET_SETTINGS_COMMAND: "model_feature_set_settings";
export const ASSISTANT_AI_TEST_CONNECTION_COMMAND: "assistant_ai_test_connection";
export const ASSISTANT_AI_OPTIMIZE_PROMPT_COMMAND: "assistant_ai_optimize_prompt";
